---
- name: Configure non-root GlusterFS geo-replication on Debian clusters
  hosts: gluster_cluster

  vars_files:
    - vars/georep.yml

  tasks:
    - name: Get glusterfs-server version
      shell: dpkg -s glusterfs-server | grep Version | cut -d " " -f2
      register: glusterfs_version

    - include: georep-pre3.9.yml
      when: glusterfs_version.stdout.find("3.8") != -1

    - include: georep-post3.9.yml
      when: glusterfs_version.stdout.find("3.10") != -1



