---
- hosts: gluster-cluster

  vars_file:
    - vars.yml

  tasks:
    - name: Add GlusterFS Debian.
      apt_repository:
        repo: deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{DEBID}}/apt {{DEBVER}} main
        state: present
        filename: 'glusterfs'
        update_cache: yes

    - name: Ensure GlusterFS will reinstall if the PPA was just added.
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - glusterfs-server
        - glusterfs-client

    - name: Ensure GlusterFS is installed.
      apt:
        name: "{{ item }}"
        state: installed
        default_release: "{{ glusterfs_default_release }}"
      with_items:
        - glusterfs-server
        - glusterfs-client
