---
- name: Deploy GlusterFS on Debian cluster
  hosts: gluster_cluster

  vars_files:
    - vars/main.yml

  tasks:
    - name: Add GlusterFS GPG key to apt
      apt_key:
        url: "http://download.gluster.org/pub/gluster/glusterfs/LATEST/rsa.pub"
        state: present
      when: ansible_architecture== "x86_64"

    - name: Add GlusterFS latest Debian repo to 64 bit nodes
      apt_repository:
        repo: "deb http://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ debian_version }}/apt {{ debian_version }} main"
        state: present
        filename: 'gluster'
        update_cache: yes
      register: new_src_repo_added
      when: ansible_architecture == "x86_64"

    - name: Add backports source repo to 32 bit nodes
      apt_repository:
        repo: "deb http://free.hands.com/debian {{ansible_distribution_release}}-backports main"
        state: present
        filename: '{{ansible_distribution_release}}-backports'
        update_cache: yes
      register: new_src_repo_added
      when: ansible_architecture == "i386"

    - name: Ensure GlusterFS reinstall if source repo was added
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - glusterfs-server
        - glusterfs-client
      when: new_src_repo_added.changed

    - name: Ensure GlusterFS is installed
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - glusterfs-server
        - glusterfs-client

    - name: Ensure GlusterFS is started and enabled at boot
      service: "name={{ glusterfs_daemon }} state=started enabled=yes"

    - name: Ensure Gluster brick directories exist
      file:
        path: "/{{ item }}/items"
        state: directory
        mode: 0775
        owner: root
        group: root
      with_sequence: start=0 end=3

    - name: Ensure GlusterFS mount directories exist
      file:
        path: "{{ gluster_mount_directory }}"
        state: directory
        mode: 0775
        owner: root
        group: root

    - name: Configure the active volume
      gluster_volume:
        state: present
        name: "{{ gluster_volume_name }}"
        brick: "/{{ item }}/items"
        cluster: "{{ ansible_play_hosts | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      with_sequence: start=0 end=3
      async: 180
      poll: 20
      run_once: true

    - name: Ensure Gluster volume is mounted
      mount:
        name: "{{ gluster_mount_directory }}"
        src: "{{ inventory_hostname }}:/{{ gluster_volume_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
